name: Test GitHub OIDC -> AWS Role

on:
  workflow_dispatch: # Run manually

permissions:
  id-token: write
  contents: read

jobs:
  test-oidc:
    environment: iwgh
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.OIDC_IAM_ROLE_ARN }}   # Full role ARN
          aws-region: ap-southeast-1

      - name: Verify AWS identity
        run: |
          echo "Checking assumed role identity..."
          aws sts get-caller-identity
