name: Test AWS OIDC

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  get-oidc-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.OIDC_IAM_ROLE_ARN }}
          aws-region: us-east-1
          role-session-name: github-actions

      - name: Print branch
        run: |
          echo "branch: $GITHUB_REF"

      - name: Request OIDC token
        id: oidc
        run: |
          TOKEN=$(curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL")
          echo "oidc_token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Decode and print sub and aud
        run: |
          OIDC_TOKEN=${{ steps.oidc.outputs.oidc_token }}
          PAYLOAD=$(echo "$OIDC_TOKEN" | cut -d'.' -f2 | base64 --decode | jq -r '.')
          echo "sub: $(echo "$PAYLOAD" | jq -r '.sub')"
          echo "aud: $(echo "$PAYLOAD" | jq -r '.aud')"